Repository pawong-refac/pawong-frontend, pull requests merged in 2025-01, with the labels that each got.

#5 Style: 로그인 페이지 퍼블리싱
  package.json
  public/assets/Login/Login_img.svg
  public/assets/Login/Logo_google.svg
  public/assets/Login/Logo_naver.svg
  public/assets/vite.svg
  src/App.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/domains/login/components/LoginSocialBtn.jsx
  src/domains/login/pages/Login.jsx
  src/domains/login/pages/LoginAdmin.jsx
  src/hooks/ScrollToTop.jsx
  src/index.css
  src/route/AppPages.jsx
  src/route/RouteDef.jsx
  tailwind.config.js
Labels: style, 은진

#9 Style: 폼 페이지 퍼블리싱
  package.json
  public/assets/UserInfo/profile_img.svg
  src/App.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/Input/Input.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/domains/Admin/components/LoginAdminModal.jsx
  src/domains/Admin/pages/LoginAdmin.jsx
  src/domains/UserInfo/components/NewUserInfoImg.jsx
  src/domains/UserInfo/pages/NewUserInfo.jsx
  src/domains/login/components/LoginSocialBtn.jsx
  src/domains/login/pages/Login.jsx
  src/domains/login/pages/LoginAdmin.jsx
  src/index.css
  src/route/RouteDef.jsx
  tailwind.config.js
Labels: refactor, style, 은진

#8 Style : 임보일지 퍼블리싱
  public/assets/Diary/IMG_3970.JPG
  public/assets/Diary/IMG_4020.JPG
  public/assets/Diary/dog-default-img.svg
  public/assets/Diary/list-img.svg
  src/domains/Diary/components/ImgUpload.jsx
  src/domains/Diary/components/dummyData.js
  src/domains/Diary/pages/AddDiary.jsx
  src/domains/Diary/pages/DetailDiary.jsx
  src/domains/Diary/pages/ListDiary.jsx
  src/index.css
  src/route/RouteDef.jsx
Labels: style, 가인
